### PR TITLE
Fixed instability of scaling system test,

### LINKED ISSUE #447: shouldNotLoseDataWhenScalingDown ocasionally fails
A couple of times I have seen this fail. Why?

Re run many times to prove stability.

### PR DESCRIPTION
**Pull request by philwinder**
Fixes #447.

### CODE REVIEW

File: system-test/src/systemTest/java/org/apache/mesos/elasticsearch/systemtest/ScalingSystemTest.java [hunk 1]
```diff
@@ -134,9 +118,21 @@ public void shouldNotLoseDataWhenScalingDown() throws UnirestException {
         assertEquals(correctNumberOfDocuments, newNumberOfDocuments);
     }
 
+    public void scaleNumNodesTo(String ipAddress, String newNumNodes) throws UnirestException {
+        HttpResponse<JsonNode> response = Unirest.put("http://" + ipAddress + ":" + WEBUI_PORT + "/v1/cluster/elasticsearchNodes").header("Content-Type", "application/json").body(newNumNodes).asJson();
```
Comment (frankscholten) [inline system-test/src/systemTest/java/org/apache/mesos/elasticsearch/systemtest/ScalingSystemTest.java]: Perhaps change newNumNodes to int?
